spring:
  application:
    name: FinalProject-MyShop
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/final-project-my-shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password: 77832005Mm
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
#  thymeleaf:
#    check-template-location: true
#    cache: false
#    prefix: file:./src/main/resources/templates/
#    resources:
#      static-locations: file:./src/main/resources/static/
#      cache-period: 0